### PR TITLE
added releaseMessage

### PR DESCRIPTION
**Pull request by dreadjr**

### CODE REVIEW

**Comment by almost** [comment]
Thanks for the pull request! Could you possibly add some tests for the new functionality?

I'm also wondering if the new method should be called changeMessageVisibility for consistency amazon's SDK, what do you think?

**Comment by almost** [comment]
Thanks, that looks great!

**Comment by dreadjr** [comment]
Great, could you cut a release and publish to npm?

**Comment by almost** [comment]
Sure, I've just published 0.2.0 with your changes

**Pull request merged**
